### ISSUE TITLE
Missing latest version of stake_layout.py ... missing USER_STAKE_INFO_ACCOUNT_LAYOUT

### ISSUE THREAD

**Issue by ezinaz** [Stochastic-Adventure/RaydiumAPYScraper#1]
Traceback (most recent call last):
  File "driver.py", line 7, in <module>
    from LPInfo import RaydiumPoolInfo
  File "C:\Users\ezinaz\Projects\raydium\RaydiumAPYScraper\LPInfo.py", line 6, in <module>
    from stake_layout import STAKE_INFO_LAYOUT_V4, STAKE_INFO_LAYOUT, OPEN_ORDERS_LAYOUT, USER_STAKE_INFO_ACCOUNT_LAYOUT
ImportError: cannot import name 'USER_STAKE_INFO_ACCOUNT_LAYOUT' from 'stake_layout' (C:\Users\ezinaz\Projects\raydium\RaydiumAPYScraper\stake_layout.py)

**Comment by douggie** [comment]
same issue

**Comment by douggie** [comment]
fixed

**Comment by Stochastic-Adventure** [comment]
The Layouts have been updated to the latest version. Closing the issue.
